# Generated by Django 5.2 on 2026-04-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek')], verbose_name='Dzień tygodnia')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('fraction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='locations.wastefractiontype', verbose_name='Rodzaj frakcji')),
            ],
            options={
                'verbose_name': 'Harmonogram odbioru',
                'verbose_name_plural': 'Harmonogram odbiorów',
                'ordering': ['day_of_week'],
            },
        ),
    ]
