# Generated by Django 5.2 on 2026-04-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionschedule',
            name='fraction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='waste.wastefractiontype', verbose_name='Rodzaj frakcji'),
        ),
    ]
