# Generated by Django 5.2 on 2026-04-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='locations.location', verbose_name='Lokalizacja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinations', to=settings.AUTH_USER_MODEL, verbose_name='Koordynator')),
            ],
            options={
                'verbose_name': 'Koordynator',
                'verbose_name_plural': 'Koordynatorzy',
                'ordering': ['location__obj_name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'location'), name='uniq_user_location')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('role', models.CharField(choices=[('REPORTER', 'ZGŁASZAJĄCY'), ('VERIFIER', 'WERYFIKATOR'), ('ADMINISTRATOR', 'ADMINISTRATOR'), ('VIEWER', 'ODWIEDZAJĄCY')], max_length=32, verbose_name='Rola')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('mpk_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpk_permissions', to='locations.mpknumber', verbose_name='Lokalizacja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpk_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Uprawnienia')),
            ],
            options={
                'verbose_name': 'Uprawnienie',
                'verbose_name_plural': 'Uprawnienia',
                'ordering': ['mpk_number__mpk_number'],
                'constraints': [models.UniqueConstraint(fields=('user', 'mpk_number', 'role'), name='uniq_user_mpk_number_role'), models.CheckConstraint(condition=models.Q(('role__in', ['REPORTER', 'VERIFIER', 'ADMINISTRATOR', 'VIEWER'])), name='chk_valid_role')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('alias', models.CharField(max_length=64, verbose_name='Alias')),
                ('department_short', models.CharField(max_length=10, verbose_name='Skrót jednostki')),
                ('department_name', models.CharField(max_length=128, verbose_name='Nazwa jednostki')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('alias',), name='uniq_alias')],
            },
        ),
    ]
