# Generated by Django 5.2 on 2026-04-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile użytkowników'},
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='uniq_alias',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alias',
        ),
    ]
