# Generated by Django 5.2 on 2026-05-09 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="Uwagi"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("EXPORT", "Eksport"), ("IMPORT", "Import")],
                        max_length=10,
                        verbose_name="Akcja",
                    ),
                ),
                ("table_name", models.CharField(max_length=100, verbose_name="Tabela")),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nazwa pliku"),
                ),
                (
                    "records_count",
                    models.IntegerField(default=0, verbose_name="Liczba rekordów"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Sukces"),
                            ("ERROR", "Błąd"),
                            ("PARTIAL", "Częściowy sukces"),
                        ],
                        default="SUCCESS",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, verbose_name="Szczegóły (błędy/ostrzeżenia)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzył",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Zmodyfikował",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rejestr transferu danych",
                "verbose_name_plural": "Rejestry transferu danych",
                "ordering": ["-created_at"],
            },
        ),
    ]
