# Generated by Django 5.2 on 2026-04-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteFractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nazwa frakcji')),
                ('code', models.IntegerField(unique=True, verbose_name='Kod frakcji')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Kategoria frakcji',
                'verbose_name_plural': 'Kategorie frakcji',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WasteFraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('capacity', models.IntegerField(verbose_name='Pojemność')),
                ('unit', models.CharField(default='l', max_length=5, verbose_name='Jednostka')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('fraction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fractions', to='waste.wastefractiontype', verbose_name='Rodzaj frakcji')),
            ],
            options={
                'verbose_name': 'Frakcja odpadów',
                'verbose_name_plural': 'Frakcje odpadów',
                'ordering': ['fraction_type__code', 'capacity'],
            },
        ),
    ]
