# Generated by Django 5.2 on 2026-05-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koszt (PLN)')),
                ('date_from', models.DateField(verbose_name='Obowiązuje od')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Obowiązuje do')),
                ('waste_fraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='waste.wastefraction', verbose_name='Frakcja')),
            ],
            options={
                'verbose_name': 'Koszt frakcji',
                'verbose_name_plural': 'Koszty frakcji',
                'db_table': 'costs',
                'ordering': ['-date_from', 'waste_fraction'],
            },
        ),
    ]
