# Generated by Django 5.2 on 2026-05-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_wastecost_created_by_wastecost_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wastecost',
            table=None,
        ),
    ]
