# Generated by Django 5.2 on 2026-04-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koszt (PLN)')),
                ('date_from', models.DateField(verbose_name='Obowiązuje od')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Obowiązuje do')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('waste_fraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='locations.wastefraction', verbose_name='Frakcja')),
            ],
            options={
                'verbose_name': 'Koszt frakcji',
                'verbose_name_plural': 'Koszty frakcji',
                'db_table': 'costs',
                'ordering': ['-date_from', 'waste_fraction'],
            },
        ),
        migrations.CreateModel(
            name='SummaryCollectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Rok')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Miesiąc')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ilość')),
                ('date_summary', models.DateField(verbose_name='Data zestawienia')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Data importu')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Zaimportował')),
                ('mpk_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='locations.mpknumber', verbose_name='Numer MPK')),
                ('waste_fraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='locations.wastefraction', verbose_name='Frakcja')),
            ],
            options={
                'verbose_name': 'Zestawienie odbioru',
                'verbose_name_plural': 'Zestawienia odbiorów',
                'db_table': 'summary_collection_schedule',
                'ordering': ['-year', '-month', 'mpk_number'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('OCZEKUJE', 'Oczekuje'), ('POTWIERDZONE', 'Potwierdzone'), ('ZATWIERDZONE', 'Zatwierdzone')], default='OCZEKUJE', max_length=16, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_monthly', to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzający')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_monthly', to=settings.AUTH_USER_MODEL, verbose_name='Potwierdzający')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_confirmations', to='locations.location', verbose_name='Lokalizacja')),
            ],
            options={
                'verbose_name': 'Potwierdzenie miesięczne',
                'verbose_name_plural': 'Potwierdzenia miesięczne',
                'db_table': 'monthly_confirmations',
                'ordering': ['-month', 'location'],
                'unique_together': {('location', 'month')},
            },
        ),
    ]
