# Generated by Django 5.2 on 2026-04-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='waste_fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='waste.wastefraction', verbose_name='Frakcja'),
        ),
        migrations.AlterField(
            model_name='summarycollectionschedule',
            name='waste_fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='waste.wastefraction', verbose_name='Frakcja'),
        ),
    ]
