# Generated by Django 5.2 on 2026-05-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_cost_waste_fraction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyconfirmation',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
