# Generated by Django 5.2 on 2026-05-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locationcontact'),
        ('reports', '0003_remove_monthlyconfirmation_notes_delete_cost'),
        ('waste', '0002_wastecost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyconfirmation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyconfirmation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlyconfirmation',
            name='mpk_number',
            field=models.ForeignKey(default=6013, on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='locations.mpknumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlyconfirmation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zatwierdzenia'),
        ),
        migrations.AlterField(
            model_name='monthlyconfirmation',
            name='status',
            field=models.CharField(choices=[('OCZEKUJE', 'Oczekuje'), ('POTWIERDZONE', 'Potwierdzone'), ('ZATWIERDZONE', 'Zatwierdzone')], default='OCZEKUJE', max_length=16),
        ),
        migrations.AlterModelTable(
            name='monthlyconfirmation',
            table=None,
        ),
        migrations.RemoveField(
            model_name='monthlyconfirmation',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='monthlyconfirmation',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='monthlyconfirmation',
            name='location',
        ),
        migrations.CreateModel(
            name='MonthlyConfirmationBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('confirmed_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.monthlyconfirmation')),
                ('waste_fraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waste.wastefraction')),
            ],
            options={
                'unique_together': {('confirmation', 'waste_fraction')},
            },
        ),
    ]
