# Generated by Django 5.2 on 2026-05-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locationcontact'),
        ('reports', '0004_alter_monthlyconfirmation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyconfirmation',
            unique_together={('mpk_number', 'month')},
        ),
    ]
