# Generated by Django 5.2 on 2026-05-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_monthlyconfirmation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconfirmation',
            name='status',
            field=models.CharField(choices=[('OCZEKUJE', 'Oczekuje'), ('POTWIERDZONE', 'Potwierdzone'), ('ZATWIERDZONE', 'Zatwierdzone'), ('KONFLIKT', 'Konflikt (Rozbieżności)')], default='OCZEKUJE', max_length=16),
        ),
        migrations.AlterField(
            model_name='monthlyconfirmationbin',
            name='confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='reports.monthlyconfirmation'),
        ),
    ]
