# Generated by Django 5.2 on 2026-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_monthlyconfirmation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconfirmationbin',
            name='confirmed_quantity',
            field=models.IntegerField(verbose_name='Potwierdzona ilość'),
        ),
    ]
