# Generated by Django 5.2 on 2026-05-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_monthlyconfirmationbin_confirmed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarycollectionschedule',
            name='quantity',
            field=models.IntegerField(verbose_name='Ilość'),
        ),
    ]
