# Generated by Django 5.2 on 2026-05-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_monthlyconfirmation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='summarycollectionschedule',
            table=None,
        ),
    ]
