# Generated by Django 5.2 on 2026-05-09 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_created_by_location_updated_by_and_more'),
        ('reports', '0010_alter_summarycollectionschedule_table'),
        ('waste', '0004_alter_wastecost_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='summarycollectionschedule',
            constraint=models.UniqueConstraint(fields=('mpk_number', 'year', 'month', 'waste_fraction'), name='uniq_summary_mpk_year_month_fraction'),
        ),
    ]
