# Generated by Django 5.2 on 2026-04-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteFractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nazwa frakcji')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Kod frakcji')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Kategoria frakcji',
                'verbose_name_plural': 'Kategorie frakcji',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MPKNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('mpk_number', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Numer MPK',
                'verbose_name_plural': 'Numery MPK',
                'ordering': ['mpk_number'],
                'constraints': [models.UniqueConstraint(fields=('mpk_number',), name='uniq_mpk_number')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('obj_name', models.CharField(max_length=200, verbose_name='Nazwa obiektu')),
                ('org_unit_name', models.CharField(max_length=20, verbose_name='Nazwa jednostki organizacyjnej')),
                ('localization', models.CharField(max_length=128, verbose_name='Lokalizacja')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('mpk_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.mpknumber', verbose_name='Lokalizacja')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
                'ordering': ['mpk_number', 'obj_name'],
            },
        ),
        migrations.CreateModel(
            name='WasteFraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('capacity', models.IntegerField(verbose_name='Pojemność')),
                ('unit', models.CharField(default='l', max_length=5, verbose_name='Jednostka')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('fraction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fractions', to='locations.wastefractiontype', verbose_name='Rodzaj frakcji')),
            ],
            options={
                'verbose_name': 'Frakcja odpadów',
                'verbose_name_plural': 'Frakcje odpadów',
                'ordering': ['fraction_type__code', 'capacity'],
            },
        ),
        migrations.CreateModel(
            name='LocationWasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość pojemników')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_bins', to='locations.location', verbose_name='Lokalizacja')),
                ('waste_fraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_bins', to='locations.wastefraction', verbose_name='Frakcja')),
            ],
            options={
                'verbose_name': 'Pojemnik lokalizacji',
                'verbose_name_plural': 'Pojemniki lokalizacji',
                'ordering': ['location', 'waste_fraction'],
                'constraints': [models.UniqueConstraint(fields=('location', 'waste_fraction'), name='uniq_location_waste_fraction')],
            },
        ),
    ]
