# Generated by Django 5.2 on 2026-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpknumber',
            name='mpk_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wastefractiontype',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Kod frakcji'),
        ),
    ]
