# Generated by Django 5.2 on 2026-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_mpknumber_mpk_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpknumber',
            name='mpk_number',
            field=models.IntegerField(),
        ),
    ]
