# Generated by Django 5.2 on 2026-04-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_mpknumber_mpk_number'),
        ('pickups', '0002_pickupwastebin_created_at_pickupwastebin_note_and_more'),
        ('reports', '0002_alter_cost_waste_fraction_and_more'),
        ('scheduling', '0002_alter_collectionschedule_fraction_type'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastefraction',
            name='fraction_type',
        ),
        migrations.AlterField(
            model_name='locationwastebin',
            name='waste_fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_bins', to='waste.wastefraction', verbose_name='Frakcja'),
        ),
        migrations.AlterModelOptions(
            name='locationwastebin',
            options={'ordering': ['location', 'waste_fraction'], 'verbose_name': 'Pojemnik w lokalizacji', 'verbose_name_plural': 'Pojemniki w lokalizacji'},
        ),
        migrations.DeleteModel(
            name='WasteFractionType',
        ),
        migrations.DeleteModel(
            name='WasteFraction',
        ),
    ]
