# Generated by Django 5.2 on 2026-05-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_wastefraction_fraction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('contact_name', models.CharField(help_text='np. Portiernia, Kierownik Magazynu, Ochrona', max_length=100, verbose_name='Nazwa kontaktu')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Numer telefonu')),
                ('active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='locations.location', verbose_name='Lokalizacja')),
            ],
            options={
                'verbose_name': 'Kontakt w lokalizacji',
                'verbose_name_plural': 'Kontakty w lokalizacjach',
                'ordering': ['location', 'contact_name'],
            },
        ),
    ]
