# Generated by Django 5.2 on 2026-04-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('note', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('pickup_number', models.CharField(max_length=15, verbose_name='Numer zgłoszenia')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('status', models.CharField(choices=[('NOWE', 'Nowe'), ('WYSŁANE', 'Wysłane'), ('POTWIERDZONE', 'Potwierdzone'), ('ZREALIZOWANE', 'Zrealizowane'), ('ODRZUCONE', 'Odrzucone')], default='NOWE', max_length=20, verbose_name='Status')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='locations.location', verbose_name='Lokalizacja')),
                ('mpk_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='locations.mpknumber', verbose_name='Numer MPK')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_pickups', to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszający')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupWasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość pojemników')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_bins', to='pickups.pickup', verbose_name='Zgłoszenie')),
                ('waste_fraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bins', to='locations.wastefraction', verbose_name='Frakcja')),
            ],
            options={
                'verbose_name': 'Frakcja zgłoszenia',
                'verbose_name_plural': 'Frakcje zgłoszenia',
                'unique_together': {('pickup', 'waste_fraction')},
            },
        ),
    ]
