# Generated by Django 5.2 on 2026-04-30 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupwastebin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickupwastebin',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Uwagi'),
        ),
        migrations.AddField(
            model_name='pickupwastebin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji'),
        ),
        migrations.AlterField(
            model_name='pickupwastebin',
            name='waste_fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bins', to='waste.wastefraction', verbose_name='Frakcja'),
        ),
    ]
