# Generated by Django 5.2 on 2026-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_pickupwastebin_created_at_pickupwastebin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='contact_phone',
            field=models.CharField(blank=b'I01\n', max_length=64, verbose_name='Telefon kontaktowy'),
        ),
    ]
