# Generated by Django 5.2 on 2026-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0004_pickup_created_by_pickup_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telefon kontaktowy'),
        ),
    ]
