# Generated by Django 5.2 on 2026-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_notification_is_active_notification_is_global_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("info", "Informacja"),
                    ("warning", "Ostrzeżenie"),
                    ("danger", "Krytyczne"),
                    ("success", "Sukces"),
                ],
                default="info",
                max_length=20,
                verbose_name="Typ alertu",
            ),
        ),
    ]
